# Site settings
title: Guerrito's in the place
email: florent@guerri.to
description: > # this means to ignore newlines until "baseurl:"
  Trying this out.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://www.guerri.to" # the base hostname & protocol for your site
twitter_username: fl0o0lf
github_username:  GueFlo

# Build settings
markdown: kramdown
